agent:
    name: OpenAIAgent
    args:
        api_key: "sk-dummy"
        api_base: "http://127.0.0.1:8000/v1" # YOUR HOSTED MODEL ADDRESS
        model_name: "Qwen/Qwen3-VL-4B-Instruct"
        max_new_tokens: 512

task:
    class: ScreenshotMobileTask_AutoTest #TextOnlyMobileTask_AutoTest
    args:
        save_dir: "./logs/evaluation"
        max_rounds: 25
        mode: in_app
        request_interval: 3
        post_action_wait: 2

eval:
  avd_name: Pixel_7_Pro_API_33
  avd_log_dir: ./logs/evaluation
  docker: True
  docker_args:
    image_name: android_eval:latest
    port: 6060
